<a href="https://colab.research.google.com/github/pythonpdnp/DL/blob/main/ANN_numParam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn

import numpy as np

### ANN net with Hidden Layer

<img src="https://github.com/pythonpdnp/DL/blob/main/img/ANNnet01.png?raw=true" width="50%" height="50%">

In [ ]:
wideNet = nn.Sequential(
    nn.Linear(2,4),
    nn.Linear(4,3)
)

deepNet = nn.Sequential(
    nn.Linear(2,2),
    nn.Linear(2,2),
    nn.Linear(2,3)
)

print(wideNet)
print(deepNet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [ ]:
for p in wideNet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[ 0.1940, -0.0775],
        [-0.5346, -0.0953],
        [-0.2081, -0.1168],
        [ 0.6363, -0.6212]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.0763,  0.6773,  0.7031, -0.3614], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[ 0.4083,  0.2218,  0.0183, -0.2624],
        [ 0.1753,  0.0364, -0.4609,  0.2568],
        [ 0.1728, -0.2780,  0.1867, -0.1076]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([ 0.4804, -0.2369, -0.3391], requires_grad=True))
 


In [ ]:
def countParam(net):
  """네트워크의 노드 수와 파라미터 수를 계산합니다.

  Args:
    net: 파라미터를 계산할 네트워크 (torch.nn.Module).

  Returns:
    튜플: (노드 수, 파라미터 수).
        노드 수는 bias 파라미터의 개수를 합산하여 계산됩니다.
        파라미터 수는 모든 파라미터 (가중치 및 bias)의 개수를 합산하여 계산됩니다.
  """
  n_nodes = 0
  n_params = 0
  for name, param in net.named_parameters():
    if 'bias' in name:
      n_nodes += param.numel()
    n_params += param.numel()

  return n_nodes, n_params

In [ ]:
wNode, wParams = countParam(wideNet)
dNode, dParams = countParam(deepNet)

print(f'Wide Net - Nodes: {wNode}, Params: {wParams}')
print(f'Deep Net - Nodes: {dNode}, Params: {dParams}')

Wide Net - Nodes: 7, Params: 27
Deep Net - Nodes: 7, Params: 21


### torchsummary

In [ ]:
from torchsummary import summary

summary(wideNet, (2,))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                    [-1, 4]              12
            Linear-2                    [-1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [ ]:
summary(deepNet, (2,))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                    [-1, 2]               6
            Linear-2                    [-1, 2]               6
            Linear-3                    [-1, 3]               9
Total params: 21
Trainable params: 21
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------
